### ISSUE TITLE
Audio issues in meetup.

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/hubs#1737]
Audio cut out and I couldn't hear anyone until the moment I tried to refresh the page.
CrimzonZA came to the meetup and could only hear Elgin. I didn't see any errors in my console -- though there were thousands of this one : https://github.com/mozilla/hubs/issues/1734

**Comment by misslivirose** [comment]
Would be great to keep an eye out for this until we get consistent repro, but there have been a few audio issues that seem a bit suspicious. I lost audio from Elgin twice in a meeting today, wonder if there's some related thing happening.

**Comment by joshmarinacci** [comment]
Surely this is fixed by now.

**Comment by misslivirose** [comment]
We still get this symptom occasionally - I think yesterday Jim couldn't hear Robin in our planning meeting, IIRC.
