### ISSUE TITLE
360 video loads in spoke (preview) but not in hubs

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs#2236]
**Description**
This video works as a 360 video in spoke, including the preview, but the hubs room fails to load with a console error.
https://www.youtube.com/watch?v=cLIMdTSLrDM

Room https://hubs.mozilla.com/PSdp3nB/scented-unruly-get-together
or scenes https://hubs.mozilla.com/scenes/dkAWLPh  https://hubs.mozilla.com/scenes/AZ5uS2c

**To Reproduce**

try out that room or those scenes.

**Expected behavior**
360 video should work.

**Comment by brianpeiris** [comment]
Looked into this briefly. It seems to be a reticulum bug. The post request we make to the media API returns a 404 almost immediately. Seems to be the case for most YouTube 360 videos I've tried so far.

**Comment by blairmacintyre** [comment]
I think for this and other media, having suggestions somewhere of where/how to store them so they do the right thing would be ideal;  most people don't _care_ about where they have to put things, they just want to know where.  Is there any place that works reliably for 360 videos?

**Comment by brianpeiris** [comment]
Any static file host should do, if the file is too big for our own 150MB upload limit (which is likely the case for 360 videos, of course). AWS S3 should be reliable.

**Comment by blairmacintyre** [comment]
Neither of those are super useful for casual users 😢   (in an age where most people don't actually have their own web servers).  

One thing I've never quite understood:  putting a file on a static webserver, will it stream correctly?  Sometimes it does, sometimes not?  Or am I stuck in the past decades where web servers didn't handle this properly?

Can I literally just drop a 360 video on one of my dreamhost servers and forget about it?

**Comment by brianpeiris** [comment]
My understanding is that most basic static web servers should do a reasonable thing and use `range` headers to stream the video a bit at a time. It should be reliable, if it's not, file a bug!

**Comment by gfodor** [comment]
I think this is just a light diligence item - we know S3 works so we
recommend it. I’m sure you could come up with flows for others that are
more user friendly - we just haven’t done it. Doesn’t need to be done by
eng unless some sites are busted we want to work

**Comment by gfodor** [comment]
iow, anyone listening just please try google drive, Dropbox, amazon drive,
literally try em all and see what works :)

**Comment by kaitas** [comment]
Thanks for your info, it seems working with Dropbox.
3.1GB MP4 (right) and 1h50m 1GB MP4 (left) in same time. Great.
https://hubs.mozilla.com/KcjsZoZ/large-file-testing

One thing I've modified URL as below:
On Dropbox sharing URL
https://www.dropbox.com/s/xxxxxx/VTC19-Full.mp4?dl=0
is replaced as below on Spoke.
https://dl.dropboxusercontent.com/s/xxxxx/VTC19-Full.mp4

**Comment by joshmarinacci** [comment]
Is this fixed now? can we mark it closed?

**Comment by mxrie-eve** [comment]
No it is not completely fixed yet. I can still reproduce the issue. I can't load any Twitch (or Vimeo) video with a 360-equirectangular projection. It does not have to be a 360-video. The same behavior is observed. That is: it will load in Spoke, but in Hubs, it shows the webpage, not the video. The second issue is that the 360-equirectangular projection doesn't work for any live stream (with Youtube, Vimeo, Twitch...)
