### ISSUE TITLE
Youtube assets shows webpage with Ad instead of video

### ISSUE THREAD

**Issue by vOwl** [mozilla/hubs#2476]
**Description**
When there is no Youtube-Premium subscription, pasted Youtube links wont show the video itself, but a rendered screenshot of the YT webpage showing a still of the/an Ad.

**To Reproduce**
1. Go to a Hubs room (without logged in YT-User or without YT-Premium subscription)
2. Paste a YT-Link like https://www.youtube.com/watch?v=ZxMaHi91RkE
3. See error

**Expected behavior**
Videos will be shown and can be watched.

**Screenshots**

**Hardware** 
 - Device: Desktop
 - OS: Win10
 - Browser: Chrome

**Additional context**

**Comment by joshmarinacci** [comment]
Is this fixed with #2583

**Comment by misslivirose** [comment]
We have a number of issues related to YouTube videos - 2583 wasn't fixed, I resolved it as a duplicate of this one but I think incorrectly, since this shows a screenshot and the other issue is just a broken media image.
