### ISSUE TITLE
Whole-room sounds out of balance with localised sounds

### ISSUE THREAD

**Issue by minim-sheba** [mozilla/hubs#4434]
**Description**
I've gone back into an existing Hubs piece today which I last touched in mid-May (at https://hubs.mozilla.com/niSUXry/haydn-space-opera ) and I'm finding that in every room that contains a heard-everywhere sound in combination with localised sounds, the balance between these two types of sound has changed although I have not touched the piece since. The balance difference is that the heard-everywhere sound is extremely quiet in relation to the localised sounds. 

For example, in the first room, the warmup singing used to be of an equivalent volume to the sounds of the videos and the main sonic focus of the space, but now can barely be heard while the video sound is prominent; in the Phyllida Barlow Playground (accessible from that first room), the main track used to be able to be clearly heard, significantly louder than the mumbled text audio (which is intentionally very quiet), but is now so quiet that the fragment of conversation at the start of it can't be heard at all, even with system volume at maximum (levels were managed to be what I felt optimal at about half-volume on my machine originally, to give scope for user adjustments in both directions).

I have changed nothing in either Spoke or Hubs since it was presented at a digital festival in May, when it was fine, and it was still fine a month ago when I captured a walkthrough for a conference presentation (link below).

**To Reproduce**
Visit [https://hubs.mozilla.com/boG8E2Q/phyllida-barlow-playground-haydn-space-opera](https://hubs.mozilla.com/boG8E2Q/phyllida-barlow-playground-haydn-space-opera):
1. Move around, note relative levels of the localised mumbling sounds (the sound by each of the individual eye videos [not part of the videos - separate sound files], group mumbling by the spawn point) to the main track which is hear-everywhere
2. compare levels with provided video of walkthrough captured a little over a month ago (doesn't start from the beginning of the room but from just before the hear-everywhere track begins with the "OK? OK... and go!" exchange - I think there's about a 30-45second lead in before it starts when you're actually in the room.) In particular, note how that OK exchange is either completely inaudible or background-volume whereas in the previous walkthrough it cuts through the other sounds to draw sonic focus.

**Expected behavior**
 View video at [https://youtu.be/qMzvIb_GsUg](https://youtu.be/qMzvIb_GsUg) to see how the balance used to be - I have changed nothing since then.

**Screenshots**
Not applicable

**Hardware** 
 - Device: Laptop
 - OS: Windows 10
 - Browser: Chrome & Firefox

**Additional context**
Also tested with headphones but it's much the same - you can hear that first exchange if you're looking for it, but it should be really clear and obvious, as per the video but it's close to inaudible.

**Comment by keianhzo** [comment]
Thanks for the detailed report. We have pushed a fix to fix this https://github.com/mozilla/hubs/pull/4444 
Let us know if everything is back to normal after that PR lands.

**Comment by minim-sheba** [comment]
Thanks keianhzo for the speedy work! Unfortunately it all seems the same. I've checked three different rooms and they're all still experiencing very low volume in the whole-room sounds compared to the localised sounds (when compared to the relative levels they used to have). I tried shift-refreshing too in case something had cached (not sure how that works with hubs) but still no change.

**Comment by keianhzo** [comment]
Sorry, maybe my message was confusing, the PR is not yet landed so it should not be fixed yet. It will land after is reviewed which will happen between today/tomorrow.

**Comment by minim-sheba** [comment]
Thanks for the clarification @keianhzo - just checking it again now and while the balance seems slightly better in that I can hear that speech section at the start of the track in the Phyllida Barlow Playground that I mentioned, I can only hear it if I'm standing right beside where the (hidden) audio file is (if I'm standing in front of the 3rd paid of eyes from the left). Indeed the whole-room sound seems to now be localised? It's very clear if I'm standing in the middle of the structure, but as soon as I fly up in the sky I can barely hear it whereas before it was a consistent level everywhere in the room. Likewise in the Warmup Room - if I stand behind the gate to the Cafe (right by the hidden sound file), I can hear the singing but nowhere else, but this used to be the main sonic focus of the space. So in both places, volume still seems to be lower than it was compared to the other (localised) elements, but now the whole-room sounds also appear to be localised.

**Comment by keianhzo** [comment]
Hi @minim-sheba The PR has been merged. Please try again and let us know if you still see the issue. Thanks for your report!

**Comment by minim-sheba** [comment]
Thanks, @keianhzo - I am delighted to say that it's all fixed! Thanks so much for your help with this. All ready for the festival relaunch now!
