### ISSUE TITLE
[MacOS][Safari 15] Rooms can't be created after the last Safari update

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4657]
**[Affected Versions]:**
- Safari 15

**[Affected Platforms]:**
- MacOS Catalina 10.15.7

**[Prerequisites]:**
- MacOS is updated having Safari 15 version.

**[Steps to reproduce]:**
1. Navigate to https://hubs.mozilla.com/.
2. Click the "Create Room" button.
3. Observe the behavior.

**[Expected results]:**
- A new room is created.

**[Actual results]:**
- A blank page and the message that a problem occurred are displayed.

**[Notes]:**
- This issue is also reproducible using Hubs Cloud.
- Attached is a screenshot of the issue:
<img width="1280" alt="Safari15" src="https://user-images.githubusercontent.com/40061643/134184405-6ce82aff-8ad3-4f29-a46e-fd7177ec7f7f.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-912)

**Comment by takahirox** [comment]
Thanks for the report. We Hubs dev team noticed this problem, too, and are investigating how to resolve.

**Comment by takahirox** [comment]
Should be fixed by https://github.com/MozillaReality/aframe/pull/31

**Comment by takahirox** [comment]
Fixed by #4658 and I confirmed that I can enter a room now with my MacOS BigSur 11.6 + Safari.

Let's close this issue if you @Softvision-RemusDranca confirm that the problem has been resolved, too.

**Comment by Softvision-RemusDranca** [comment]
@takahirox  Unfortunately I can still reproduce the issue on my MacOS Catalina 10.15.7. What's different is that now the device mic permissions prompt is displayed and also the Hubs UI where the page is loading can be visible shortly. 
- Video: [link](https://drive.google.com/file/d/1RWwLK-vY9IaUp8fGmCtb9k3-9qkcsp7w/view?usp=sharing).
- Logs: [link](https://drive.google.com/file/d/1BFNeV6YsFZjH7_tR1HnZJ-AQI0xf0lf9/view?usp=sharing).

**Comment by takahirox** [comment]
As we discussed internally, it may be safe to say that most MacOS users use BigSur. We may be able to suggest Catalina users to upgrade MacOS or use MacOS Chrome/Firefox instead.

If you @Softvision-RemusDranca confirm that the problem is not reproducible on your BigSur, let's close this issue.

**Comment by Softvision-RemusDranca** [comment]
@takahirox  I confirm that the issue is not reproducible after upgrading to Big Sur 11.6 using Safari 15.
I was thinking of keeping the issue opened for now so that users will have an indicator in case they encounter it and we could lower the severity since it's reproducible on a specific version of macOS. 
Please share your thoughts on this idea, thanks!

**Comment by takahirox** [comment]
Some one seem to have accidentally or intentionally closed this issue in Jira side.

> I was thinking of keeping the issue opened for now so that users will have an indicator in case they encounter it and we could lower the severity since it's reproducible on a specific version of macOS.

I think it very depends on the Catalina share but as we internally discussed the actual Catalina share number is unfortunately unclear. So I don't have my big preference.

If we want to keep this issue opened, at least we need to add a label which indicates we won't fix (unless we have many requests). Maybe replacing "QA[Blocker-issue]" with "QA [Wontfix-issue]" label may be good?
